version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "a2e-tsdat-pipelines"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-rq99cgy93a46"
s3_prefix = "a2e-tsdat-pipelines"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = ["A2ETsdatPipelines=332883119153.dkr.ecr.us-west-2.amazonaws.com/a2e-tsdat-test"]
parameter_overrides = "SourceBucket=\"a2e-tsdat-pipeline-inputs\" DestinationBucket=\"a2e-tsdat-pipeline-outputs\" LoggingLevel=\"DEBUG\""

